# Generated by Django 4.2.10 on 2024-02-21 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='app_images/')),
                ('link', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('entertainment', 'Entertainment'), ('sports', 'Sports'), ('health', 'Health'), ('education', 'Education')], max_length=20)),
                ('subcategory', models.CharField(blank=True, choices=[], max_length=20)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='userapp_screenshots/')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='next.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userapp',
            constraint=models.UniqueConstraint(fields=('user', 'app'), name='unique_user_app'),
        ),
    ]
