# Generated by Django 4.2.10 on 2024-02-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('next', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='subcategory',
            field=models.CharField(max_length=20),
        ),
    ]
